import { expect, test } from '@playwright/test';
import { bootstrapOrLoginAdmin, collectPageDiagnostics, createList } from './helpers';

test.describe('Planning release candidate @planning @smoke', () => {
  test.use({ timezoneId: 'Europe/Berlin' });
  test('reviews local dated work, completes it and rejects a stale overview', async ({ page }, info) => {
    const diagnostics = collectPageDiagnostics(page);
    await bootstrapOrLoginAdmin(page);
    const title = `Agenda ${info.project.name}`;
    const list = await (await page.request.post('/api/v1/lists', { data: { title, type: 'TODO' } })).json();
    const dates = await page.evaluate(() => [-1, 0, 1].map(offset => {
      const today = new Date(); return new Date(today.getFullYear(), today.getMonth(), today.getDate() + offset, 12).toISOString();
    }));
    const tasks = [];
    for (const [i, name] of ['Overdue call', 'Today call', 'Tomorrow call'].entries()) {
      const response = await page.request.post(`/api/v1/lists/${list.id}/items`, { data: { name: `${name} ${info.project.name}`, dueDate: dates[i] } });
      expect(response.status()).toBe(201); tasks.push(await response.json());
    }
    await page.request.post(`/api/v1/lists/${list.id}/items`, { data: { name: 'Undated task' } });
    await page.reload();
    await page.getByRole('button', { name: 'Today & upcoming', exact: true }).click();
    const hub = page.locator('.planning-hub');
    await expect(hub.locator('.overdue')).toContainText(`Overdue call ${info.project.name}`);
    await expect(hub.locator('.today')).toContainText(`Today call ${info.project.name}`);
    await expect(hub.locator('.upcoming')).toContainText(`Tomorrow call ${info.project.name}`);
    await expect(hub).not.toContainText('Undated task');
    await expect(hub).toContainText('Europe/Berlin');
    await page.screenshot({ path: `/tmp/listful-rc-${info.project.name}-today.png`, fullPage: true });
    await hub.getByRole('button', { name: `Done: Today call ${info.project.name}`, exact: true }).click();
    await expect(hub.locator('.today')).not.toContainText(`Today call ${info.project.name}`);
    const upcoming = tasks[2];
    expect((await page.request.put(`/api/v1/items/${upcoming.id}`, { headers: { 'If-Match': `"${upcoming.version}"` }, data: { name: upcoming.name, dueDate: upcoming.dueDate, description: 'Edited elsewhere' } })).status()).toBe(200);
    await hub.getByRole('button', { name: `Done: Tomorrow call ${info.project.name}`, exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('This item changed');
    expect((await (await page.request.get(`/api/v1/items/${upcoming.id}`)).json()).status).toBe('OPEN');
    await hub.getByRole('button', { name: 'Refresh', exact: true }).click();
    await expect(page.getByRole('alert')).toHaveCount(0);
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await diagnostics.expectClean();
  });

  test('archives lists and restores deleted lists and items even after reload', async ({ page }, info) => {
    await bootstrapOrLoginAdmin(page);
    const title = `Recoverable ${info.project.name}`;
    await createList(page, title, 'TODO');
    await page.getByLabel('New item name', { exact: true }).fill('Keep this task');
    await page.getByRole('button', { name: 'Add item', exact: true }).click();
    await page.getByRole('button', { name: 'List settings', exact: true }).click();
    await page.getByRole('button', { name: 'Archive list', exact: true }).click();
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'List settings', exact: true }).click();
    await page.getByRole('button', { name: 'Archive list', exact: true }).click();
    await page.getByRole('button', { name: 'Archive', exact: true }).click();
    let card = page.locator('.library-card').filter({ has: page.getByRole('heading', { name: title, exact: true }) });
    await card.getByRole('button', { name: 'Open list', exact: true }).click();
    await expect(page.getByText('Keep this task', { exact: true })).toBeVisible();
    await expect(page.locator('.composer-disclosure')).toHaveCount(0);
    await expect(page.locator('.item-actions')).toHaveCount(0);
    await page.getByRole('button', { name: 'List settings', exact: true }).click();
    await page.getByRole('button', { name: 'Restore', exact: true }).click();
    await page.getByLabel('More: Keep this task', { exact: true }).click();
    page.once('dialog', dialog => dialog.accept());
    await page.getByRole('button', { name: 'Delete: Keep this task', exact: true }).click();
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect(page.getByText('Keep this task', { exact: true })).toBeVisible();
    await page.getByLabel('More: Keep this task', { exact: true }).click();
    page.once('dialog', dialog => dialog.accept());
    await page.getByRole('button', { name: 'Delete: Keep this task', exact: true }).click();
    await page.reload();
    await page.getByRole('button', { name: 'Trash', exact: true }).click();
    await expect(page.locator('.trash-items')).toContainText('Keep this task');
    await page.getByRole('button', { name: 'Restore: Keep this task', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Restore: Keep this task', exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: 'Your lists', exact: true }).click();
    await expect(page.getByText('Keep this task', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'List settings', exact: true }).click();
    await page.getByRole('button', { name: 'Delete list', exact: true }).click();
    await page.getByRole('button', { name: 'Confirm delete', exact: true }).click();
    await page.reload();
    await page.getByRole('button', { name: 'Trash', exact: true }).click();
    card = page.locator('.library-card').filter({ has: page.getByRole('heading', { name: title, exact: true }) });
    await page.screenshot({ path: `/tmp/listful-rc-${info.project.name}-trash.png`, fullPage: true });
    await card.getByRole('button', { name: 'Restore', exact: true }).click();
    await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible();
    await expect(page.getByText('Keep this task', { exact: true })).toBeVisible();
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  });

  test('saves a reusable event blueprint and creates fresh independently named lists', async ({ page }, info) => {
    await bootstrapOrLoginAdmin(page);
    const title = `Reusable party ${info.project.name}`;
    await createList(page, title, 'EVENT');
    await page.getByLabel('New item name', { exact: true }).fill('Book the venue');
    await page.locator('.item-details > summary').click();
    await page.locator('.item-composer').getByLabel('Due date').fill('2027-05-01T10:00');
    await page.locator('.item-composer').getByLabel('Owner / responsible').fill('Alex');
    await page.getByRole('button', { name: 'Add item', exact: true }).click();
    await page.getByRole('button', { name: 'Done: Book the venue', exact: true }).click();
    await page.getByRole('button', { name: 'List settings', exact: true }).click();
    await page.getByRole('button', { name: 'Save as template', exact: true }).click();
    const form = page.locator('.save-template-form');
    const templateTitle = `Party blueprint ${info.project.name}`;
    await form.getByLabel('Template name').fill(templateTitle);
    await form.getByRole('button', { name: 'Save as template', exact: true }).click();
    let card = page.locator('.library-card').filter({ has: page.getByRole('heading', { name: templateTitle, exact: true }) });
    await card.getByRole('button', { name: 'Use template', exact: true }).click();
    await card.getByLabel('New list name').fill(`Fresh party ${info.project.name}`);
    await expect(card.getByLabel('Target date')).toHaveValue('');
    await card.getByLabel('Target date').fill('2028-06-10T14:00');
    await page.screenshot({ path: `/tmp/listful-rc-${info.project.name}-templates.png`, fullPage: true });
    await card.getByRole('button', { name: 'Create from template', exact: true }).click();
    await expect(page.getByRole('heading', { name: `Fresh party ${info.project.name}`, exact: true })).toBeVisible();
    await expect(page.getByText('1 open · 1 total', { exact: true })).toBeVisible();
    await expect(page.getByText('Owner / responsible: Alex', { exact: true })).toBeVisible();
    const lists = await (await page.request.get('/api/v1/lists')).json();
    const fresh = lists.find((list: { title: string }) => list.title === `Fresh party ${info.project.name}`);
    const items = await (await page.request.get(`/api/v1/lists/${fresh.id}/items`)).json();
    expect(items[0].dueDate).toBeNull(); expect(items[0].status).toBe('OPEN'); expect(fresh.publicList).toBe(false);
    await page.getByRole('button', { name: 'Templates', exact: true }).click();
    card = page.locator('.library-card').filter({ has: page.getByRole('heading', { name: templateTitle, exact: true }) });
    await card.getByRole('button', { name: 'Open list', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Sharing', exact: true })).toHaveCount(0);
    await expect(page.getByRole('button', { name: 'Done: Book the venue', exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: 'Templates', exact: true }).click();
    card = page.locator('.library-card').filter({ has: page.getByRole('heading', { name: templateTitle, exact: true }) });
    page.once('dialog', dialog => dialog.accept());
    await card.getByRole('button', { name: 'Delete template', exact: true }).click();
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    await expect(page.getByRole('heading', { name: templateTitle, exact: true })).toBeVisible();
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  });
});
